version: '3.8'

services:
  database:
    image: 'mysql:8'
    environment:
      MYSQL_DATABASE: 'homesplit_dev'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'secure_password'
      MYSQL_ROOT_PASSWORD: 'secure_password'
    volumes:
      - database:/var/lib/mysql
    ports:
      - '3360:3306'
volumes:
  database: