import datetime
from email.policy import default
from typing import Optional
from fastapi import FastAPI
from .models import User
from sqlmodel import Field, Session, SQLModel, create_engine

app = FastAPI()


engine = create_engine('mysql+aiomysql://app:secure_password@127.0.0.1:3360/homesplit_dev', echo=True)

@app.get("/")
async def hello_world():
    return {"message": "Hello world!!!!!!!!!!!!!!!!!&"}


#Keep, takes params, need to create entry
@app.get("/addDebt")
async def addDebt(principal: float = 0, remaining: float = 0, interest_rate: float=4, term_days: int=10950):
    #now = datetime.datetime.now()
    term_years=term_days/365
    return {"principal":{principal},"remaining":{remaining},"interest rate": {interest_rate}, "term days":{term_days}, "term years": {term_years}, "created at": {now}, "last updated":{now}}


#Keep, takes params, need to create entry
@app.post("/users")
async def create_user(user: User):
    print(user) 
    # turn params into User object
    new_user=User(first_name=user.first_name,last_name=user.last_name,email=user.email)
    print(new_user)
    #open Session, use .add
    session = Session(engine)
    session.add(new_user)
    
    print(session)
    
    #session.commit()
    #session.close()

    #get new objects new autogenerated id and return that
    fake_id=1
    return {"id":{fake_id},}

